name: CI/CD Pipeline
on:
  push:
    branches:
      - test

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghtempconv1
      PROJECT_ID: tempconv1-389923
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet

      - name: Push Docker image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run using new key
        run: |
          docker pull gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          gcloud run deploy ghtempconv1 --image gcr.io/$PROJECT_ID/$IMAGE_NAME:latest --platform managed --region us-central1 --allow-unauthenticated

  get-deployment-url:
    name: Get Cloud Run Deployment URL
    needs: build-push-gcr
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Get Deployment URL
        id: get-url
        run: |
         echo "Cloud Run Deployment URL: https://$(gcloud run services describe ghtempconv1 --platform managed --region us-central1 --format 'value(status.url)' --project=${{ env.PROJECT_ID }})"



      - name: Display Deployment URL
        run: |
          echo "${{ steps.get-url.outputs.url }}"
