name: CI/CD Pipeline
on:
  push:
    branches:
      - test

jobs:
  build-push-gcr:
    name: build and push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghtempconv1
      PROJECT_ID: tempconv1-389923
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY}}
          project_id: ${{ env.PROJECT_ID}}
          export_default_credentials: true

      - name: build Docker Image
        run: |docker build -t $IMAGE_NAME:latest .  

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet

      - name: Push Docker image to container registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID//$IMAGE_NAME:latest 
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy --image gcr.io/tempconv1-389923/ghapp:${{ github.sha }} --platform managed --region us-central1 --allow-unauthenticated
