name: CI/CD Pipeline
on:
  push:
    branches:
      - test

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghtempconv1
      PROJECT_ID: tempconv1-389923
    steps:
      # ... existing steps ...

  get-deployment-url:
    name: Get Cloud Run Deployment URL
    needs: build-push-gcr
    runs-on: ubuntu-latest

    steps:
      # ... existing steps ...

      - name: Display Deployment URL
        run: |
          echo "Cloud Run Deployment URL: ${{ steps.get-url.outputs.url }}"
