name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json --project=tempconv1-389923
          gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/tempconv1-389923/ghapp:${{ github.sha }} .
          docker push gcr.io/tempconv1-389923/ghapp:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy --image gcr.io/tempconv1-389923/ghapp:${{ github.sha }} --platform managed --region us-central1 --allow-unauthenticated
