name: CI/CD Pipeline
on:
  push:
    branches:
      - test

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghtempconv1
      PROJECT_ID: tempconv1-389923
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet

      - name: Push Docker image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run using new key
        run: |
          gcloud run deploy tem45 --image gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} --platform managed --region us-central1 --allow-unauthenticated
      
     